CREATE TABLE cars (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  carModelId BIGINT NOT NULL,
  ownerId BIGINT NOT NULL,

  stateNumber VARCHAR NOT NULL UNIQUE,
  vinNumber VARCHAR NOT NULL UNIQUE,

  additionalInfo VARCHAR,

  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);
