CREATE TABLE owners (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,

  name VARCHAR NOT NULL,
  surname VARCHAR NOT NULL,
  phone VARCHAR NOT NULL,
  email VARCHAR NOT NULL,

  address VARCHAR NOT NULL,
  city VARCHAR NOT NULL,
  postalCode VARCHAR NOT NULL,
------

  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);
