CREATE TABLE penalties (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  carId BIGINT NOT NULL,
  inspectorId BIGINT NOT NULL,
  penaltyTypeId BIGINT NOT NULL,

  amount DECIMAL(15,2),
  additionalInfo VARCHAR,
  place VARCHAR,

  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
